
safe: true
exclude:
  - offenerhaushalt/*
  - build/*
  - Makefile
  - LICENSE
  - README.md
  - bower.json
  - old/*
  - exports/*
  - bower_components/*

api_base: http://db.offenerhaushalt.de/api/babbage/cubes/

collections:
  budgets:
    output: true
    permalink: /haushalt/:path/

defaults:
  - scope:
      path: ""
      type: budgets
    values:
      layout: budget
