
safe: true
exclude:
  - offenerhaushalt/*
  - build/*
  - Makefile
  - LICENSE
  - README.md
  - bower.json
  - contrib/*
  - exports/*
  - bower_components/*

sass:
  style: compressed
  sass_dir: style


collections:
  budgets:
    output: true
    permalink: /haushalt/:path/

defaults:
  - scope:
      path: ""
      type: budgets
    values:
      layout: budget
